import { Inter } from "next/font/google";

import { Box } from "@mui/material";

// Theme Registery
import ThemeRegistry from "@/theme/ThemeRegistery";

// @ custom components
import { Navigation } from "@/components/nav";

import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"], weights: [400, 500, 600, 700] });

export const metadata = {
  title: "Gogreenbooty - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const mobileOpen = false
  // const handleDrawerToggle = () => {

  // }

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={inter.className}>
        <ThemeRegistry>
          <Navigation />
          <Box
            component="div"
            sx={{ position: "relative", top: 143, height: "100%" }}
          >
            {children}
          </Box>
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}
